// Versioned existing FuelCheck importer. Runtime credential fallback is supplied by the private deployment entrypoint.
let legacyBasic = "";
function adminKey(){try{const x=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}");if(x.default)return x.default}catch{}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||""}
function adminHeaders(extra:any={}){const k=adminKey();return {apikey:k,authorization:"Bearer "+k,"content-type":"application/json",...extra}}
async function configValue(key:string){const r=await fetch((Deno.env.get("SUPABASE_URL")||"")+"/rest/v1/fueldrop_private_config?select=value&key=eq."+encodeURIComponent(key)+"&limit=1",{headers:adminHeaders()});if(!r.ok)return null;const a=await r.json();return Array.isArray(a)&&a[0]?.value?String(a[0].value):null}
async function authorized(req:Request){const supplied=req.headers.get("x-cron-secret")||"";if(supplied){const expected=await configValue("cron_secret");if(expected&&supplied===expected)return true}const key=adminKey();return Boolean(key&&req.headers.get("apikey")===key)}
function basicAuth(){return (Deno.env.get("NSW_FUEL_BASIC_AUTH")||legacyBasic).trim()}
function apiKey(){const explicit=(Deno.env.get("NSW_FUEL_API_KEY")||"").trim();if(explicit)return explicit;try{return atob(basicAuth().replace(/^Basic\s+/i,"")).split(":")[0]||""}catch{return ""}}
async function accessToken(){const r=await fetch("https://api.onegov.nsw.gov.au/oauth/client_credential/accesstoken?grant_type=client_credentials",{method:"GET",headers:{Authorization:basicAuth(),Accept:"application/json","Content-Type":"application/json"}});const text=(await r.text()).trim();if(!r.ok)throw new Error("fuelcheck_oauth_"+r.status);try{const j=JSON.parse(text),t=j.access_token||j.accessToken||j.token;if(t)return String(t)}catch{}throw new Error("fuelcheck_oauth_invalid_response")}
function requestTimestamp(){const p=new Intl.DateTimeFormat("en-AU",{timeZone:"Australia/Sydney",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:true}).formatToParts(new Date()),g=(t:string)=>p.find(x=>x.type===t)?.value||"";return g("day")+"/"+g("month")+"/"+g("year")+" "+g("hour")+":"+g("minute")+":"+g("second")+" "+g("dayPeriod")}
async function fuelcheck(state:string,token:string){const url=state==="ACT"?"https://api.onegov.nsw.gov.au/FuelPriceCheck/v1/fuel/prices":"https://api.onegov.nsw.gov.au/FuelPriceCheck/v2/fuel/prices?states="+encodeURIComponent(state);const r=await fetch(url,{headers:{Authorization:"Bearer "+token,apikey:apiKey(),transactionid:crypto.randomUUID(),requesttimestamp:requestTimestamp(),"Content-Type":"application/json; charset=utf-8",Accept:"application/json"}});if(!r.ok)throw new Error("fuelcheck_"+state.toLowerCase()+"_"+r.status);const j=await r.json();let stations=Array.isArray(j?.stations)?j.stations:[],prices=Array.isArray(j?.prices)?j.prices:[];if(state==="ACT"){stations=stations.filter((x:any)=>String(x?.state||"").toUpperCase()==="ACT");prices=prices.filter((x:any)=>String(x?.state||"").toUpperCase()==="ACT")}return {stations,prices}}
export function appFuel(code:any){const c=String(code||"").toUpperCase();return c==="DL"?"Diesel":c==="PDL"?"Premium Diesel":c==="U91"?"U91":c==="E10"?"E10":c==="P95"?"U95":c==="P98"?"U98":null}
function localDate(tz:string){const p=new Intl.DateTimeFormat("en-AU",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),g=(t:string)=>p.find(x=>x.type===t)?.value||"";return g("year")+"-"+g("month")+"-"+g("day")}
function zonedLocalToIso(v:any,tz:string){const m=String(v||"").match(/^(\d{2})\/(\d{2})\/(\d{4})\s+(\d{2}):(\d{2}):(\d{2})$/);if(!m)return null;const target=Date.UTC(Number(m[3]),Number(m[2])-1,Number(m[1]),Number(m[4]),Number(m[5]),Number(m[6]));const parts=(ms:number)=>{const p=new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(new Date(ms)),g=(t:string)=>Number(p.find(x=>x.type===t)?.value||0);return Date.UTC(g("year"),g("month")-1,g("day"),g("hour"),g("minute"),g("second"))};let guess=target-(parts(target)-target);guess=target-(parts(guess)-guess);return new Date(guess).toISOString()}
function addressParts(address:any,state:string){const a=String(address||"").trim(),m=a.match(/,?\s*([^,]+?)\s+(NSW|TAS)\s+(\d{4})\s*$/i);return {suburb:m?String(m[1]).trim():null,postcode:m?m[3]:null}}
async function upsert(table:string,conflict:string,rows:any[]){const base=Deno.env.get("SUPABASE_URL")||"";let total=0;for(let i=0;i<rows.length;i+=500){const chunk=rows.slice(i,i+500);if(!chunk.length)continue;const r=await fetch(base+"/rest/v1/"+table+"?on_conflict="+encodeURIComponent(conflict),{method:"POST",headers:adminHeaders({prefer:"resolution=merge-duplicates,return=minimal"}),body:JSON.stringify(chunk)});if(!r.ok)throw new Error("supabase_"+table+"_upsert_"+r.status);total+=chunk.length}return total}
async function cleanup(table:string,syncedAt:string,filter:string){const r=await fetch((Deno.env.get("SUPABASE_URL")||"")+"/rest/v1/"+table+"?synced_at=lt."+encodeURIComponent(syncedAt)+"&"+filter,{method:"DELETE",headers:adminHeaders({prefer:"return=minimal"})});if(!r.ok)throw new Error("supabase_"+table+"_cleanup_"+r.status)}
async function mark(state:string,status:string,records=0,error_message:string|null=null){await upsert("fuel_sync_state","provider_code,fuel_type",[{provider_code:"nsw-fuelcheck",fuel_type:state,last_attempt_at:new Date().toISOString(),last_success_at:status==="ok"?new Date().toISOString():null,status,records_received:records,error_message,updated_at:new Date().toISOString()}])}
export function priceRowsForSnapshot(data:any,state:string,priceDate:string,syncedAt:string){
 const tz=state==="TAS"?"Australia/Hobart":"Australia/Sydney",stationMap=new Map<string,any>();
 for(const s of data.stations){const code=String(s?.code??"").trim(),lat=Number(s?.location?.latitude),lng=Number(s?.location?.longitude);if(!code||s?.location?.latitude==null||s?.location?.longitude==null||!Number.isFinite(lat)||!Number.isFinite(lng)||lat < -90||lat > 90||lng < -180||lng > 180)continue;const parts=addressParts(s?.address,state),row={station_id:state+"-"+code,provider_station_id:code,state_code:state,provider_code:"nsw-fuelcheck",region_name:parts.suburb,station_name:String(s?.name||"Fuel station"),brand:String(s?.brand||"")||null,suburb:parts.suburb,address:String(s?.address||""),postcode:parts.postcode,latitude:lat,longitude:lng,source_modified_at:null,synced_at:syncedAt};stationMap.set(code,row)}
 const prices=new Map<string,any>();
 for(const p of data.prices){const code=String(p?.stationcode??"").trim(),site=stationMap.get(code),fuel=appFuel(p?.fueltype),price=Number(p?.price);if(!site||!fuel||!Number.isFinite(price)||price<=0)continue;const row={station_id:site.station_id,state_code:state,provider_code:"nsw-fuelcheck",fuel_type:fuel,price_date:priceDate,station_name:site.station_name,brand:site.brand,suburb:site.suburb,address:site.address,postcode:site.postcode,latitude:site.latitude,longitude:site.longitude,price,transaction_date_utc:zonedLocalToIso(p?.lastupdated,tz),synced_at:syncedAt};prices.set(row.station_id+"|"+fuel+"|"+priceDate,row)}
 return {sites:[...stationMap.values()],prices:[...prices.values()]};
}
async function syncState(state:string,token:string){const tz=state==="TAS"?"Australia/Hobart":"Australia/Sydney",priceDate=localDate(tz),syncedAt=new Date().toISOString();await mark(state,"running");try{const data=await fuelcheck(state,token),{sites,prices}=priceRowsForSnapshot(data,state,priceDate,syncedAt);if(!sites.length||!prices.length)throw new Error("fuelcheck_empty_snapshot_refused");const sw=await upsert("fuel_site_reference","station_id",sites),pw=await upsert("fuel_price_daily","station_id,fuel_type,price_date",prices);await cleanup("fuel_site_reference",syncedAt,"state_code=eq."+state+"&provider_code=eq.nsw-fuelcheck");await cleanup("fuel_price_daily",syncedAt,"state_code=eq."+state+"&provider_code=eq.nsw-fuelcheck&price_date=eq."+priceDate);await mark(state,"ok",pw,null);return {state,stations:sw,prices:pw,rawPrices:data.prices.length,priceDate,syncedAt}}catch(e){const msg=String(e?.message||e);try{await mark(state,"error",0,msg)}catch{}return {state,ok:false,error:msg}}}
export async function fuelcheckHandler(req:Request){if(!await authorized(req))return Response.json({ok:false,error:"unauthorized"},{status:401});try{const token=await accessToken(),requested=new URL(req.url).searchParams.get("state")?.toUpperCase(),states=requested==="NSW"||requested==="TAS"||requested==="ACT"?[requested]:["NSW","TAS"],results=[];for(const state of states)results.push(await syncState(state,token));const ok=results.every((x:any)=>x.ok!==false);return Response.json({ok,provider:"NSW Government FuelCheck",trialCredential:!Deno.env.get("NSW_FUEL_BASIC_AUTH"),results},{status:ok?200:502})}catch(e){return Response.json({ok:false,error:String(e?.message||e)},{status:502})}}
export function startFuelcheckSync(fallbackBasic=""){legacyBasic=fallbackBasic;Deno.serve(fuelcheckHandler)}
