from pathlib import Path
p=Path('web/nearby-ui.js');s=p.read_text()
s=s.replace('function destinationChanged(){','function destinationChanged(event){').replace("if(read('fmnDestinationFilterKey',null)!==key){","if(event?.detail?.changed===true||read('fmnDestinationFilterKey',null)!==key){")
s=s.replace("function mapCaption(){const f=useFilters();return", "function mapCaption(){const f=useFilters();if(window.FMNJourney?.getDestination()?.manual)return 'Destination needs an area suggestion · not filtered';return")
s=s.replace("const s=document.getElementById('nearbyFilterSummary');s.textContent=summary(lastList.length,lastCount);", "const s=document.getElementById('nearbyFilterSummary');s.textContent=summary(lastList.length,lastCount)+(window.FMNJourney?.getDestination()?.manual?' Destination is saved for external Maps only. Choose an area suggestion to filter here.':'');")
p.write_text(s)
p=Path('web/journey.js');s=p.read_text()
s=s.replace("function renderDestination(){document.dispatchEvent(new Event('fmn:destination'));","function renderDestination(changed=false){document.dispatchEvent(new CustomEvent('fmn:destination',{detail:{changed}}));")
s=s.replace('const saved=writeDestination();renderDestination();','const saved=writeDestination();renderDestination(true);')
s=s.replace("cancelLocation();app.closeArea();root.FMNLiveLocation?.start();","cancelLocation();app.closeArea();app.openExplore();root.FMNLiveLocation?.start();")
s=s.replace("'Saved destination: '+destination.label", "(destination.manual?'External Maps only — select an area suggestion to filter stations: ':'Saved destination: ')+destination.label")
s=s.replace("b.type='button';b.onclick=()=>saveDestination(clean);", "b.type='button';b.dataset.geocoded='true';b.onclick=()=>saveDestination(clean);")
s=s.replace("const manual=element('button','Use “'+query+'” as destination in Maps','journey-result');", "const manual=element('button','External Google Maps only: “'+query+'” (does not filter stations)','journey-result');")
s=s.replace('box.append(manual);}}}', "if(!box.querySelector('[data-geocoded=true]'))box.append(manual);}}}")
p.write_text(s)
p=Path('web/index.html');s=p.read_text().replace('openArea:openArea,closeArea:closeArea,toast:toast,','openArea:openArea,closeArea:closeArea,openExplore:function(){showPage("explore")},toast:toast,');p.write_text(s)
print('Explicit destination selection activates filtering; opening a dialog respects All directions; Maps-only text is labelled.')
