/* FillMeNow journey UI. No background tracking; location is requested only on a user action. */
(function(root,factory){'use strict';const core=factory();if(typeof module==='object'&&module.exports){module.exports=core;return;}root.FMNJourneyCore=core;
let app,controller=null,sequence=0,searchController=null,searchSequence=0,searchTimer=null,pendingPoint=null;
let destination=core.cleanDestination(read('fmnJourney',null));
function read(k,d){try{return JSON.parse(localStorage.getItem(k))||d;}catch{return d;}}
function writeDestination(){try{if(destination)localStorage.setItem('fmnJourney',JSON.stringify(destination));else localStorage.removeItem('fmnJourney');return true;}catch{return false;}}
function $(id){return document.getElementById(id);}
function element(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function status(text,kind){const n=$('locationStatus');if(n){n.textContent=text;n.dataset.state=kind||'info';n.hidden=!text;}}
function busy(active){[$('gpsBtn'),$('areaGps')].filter(Boolean).forEach(b=>{b.disabled=active;b.style.opacity='';b.setAttribute('aria-busy',String(active));});if($('areaGps'))$('areaGps').textContent=active?'Finding your location…':'Use current location';if($('locationCancel'))$('locationCancel').hidden=!active;}
function cancelLocation(manual=false){sequence++;controller?.abort();controller=null;busy(false);pendingPoint=null;if($('locationUseSelectedState'))$('locationUseSelectedState').hidden=true;if(manual)status('Use a suburb or postcode below. Location permission is optional.');}
function help(){const d=dialog('Allow location'),body=d.querySelector('.journey-scroll');body.append(element('p','FillMeNow cannot turn on your phone location or override a blocked permission. You control both settings.'),element('p','Android: turn on phone Location. In Settings → Apps → Chrome (or your browser) → Permissions → Location, enable Use precise location. Also open this same FillMeNow address → site information → Permissions → Location, allow it and choose Precise if offered. Both permissions matter.'),element('p','For an installed shortcut, open this same app address in your browser to review its permission. Then return and tap Use current location.'),element('p','iPhone: enable Location Services in Settings → Privacy & Security, and allow your browser to request location. You can always search manually instead.'));
root.FMNPermissionUI?.mount(body,()=>{d.close();requestLocation();});
const retry=element('button','Try location again');retry.type='button';retry.onclick=()=>{d.close();requestLocation();};d.querySelector('footer').append(retry);}
async function requestLocation(){if(!app)return;cancelLocation();app.openArea();const id=++sequence;controller=new AbortController();const signal=controller.signal;busy(true);status('Choose Allow if your phone asks. You can cancel and search manually at any time.','pending');
try{if(!root.isSecureContext)throw {code:'insecure'};if(!navigator.geolocation)throw {code:'unsupported'};const policy=document.permissionsPolicy||document.featurePolicy;if(policy&&typeof policy.allowsFeature==='function'&&!policy.allowsFeature('geolocation'))throw {code:'policy'};
root.FMNLiveLocation?.stop();
const p=await core.locate(navigator.geolocation,{signal,onQuality:info=>{if(id===sequence)status(info.code==='precision'?'Your phone is returning approximate location (±'+Math.round(info.accuracy)+' m). Waiting for precise GPS. Check Location permission help.':'Waiting for a fresh precise GPS position…','pending');}});if(id!==sequence)return;busy(false);controller=null;
const result=app.acceptGPS(p);if(!result.ok){pendingPoint=p;status(result.reason==='coverage'?'This state is temporarily unavailable. Choose a different area or retry shortly.':'Your location is near a state boundary or outside automatic state detection. Select the correct state, then confirm below.');if(result.reason==='border')$('locationUseSelectedState').hidden=false;return;}
status('Precise location found (reported ±'+Math.round(p.accuracy)+' m).','ready');
}catch(e){if(id!==sequence||e?.name==='AbortError')return;busy(false);controller=null;
const messages={precision:'Only approximate location was supplied. Enable Precise location for both this site and your browser, then retry. Your search location has not been moved.',1:'Location is blocked. Allow location for this app in your browser and phone settings, then try again.',2:'Your phone could not determine its location. Turn on Location, try again, or search a suburb below.',3:'Location took too long. Check the permission prompt and your phone Location setting, or search manually.',insecure:'Location needs a secure connection. Open the HTTPS FillMeNow app or search manually.',unsupported:'Location is not supported here. Open FillMeNow in your browser or search a suburb.',policy:'This browser window blocks location. Open FillMeNow directly in your browser or search manually.'};status(messages[e?.code]||'Location could not be obtained. Try again or search a suburb below.','error');}}
function dialog(title){const old=$('journeyDialog');if(old)old.close();const d=element('dialog',undefined,'journey-dialog');d.id='journeyDialog';d.setAttribute('aria-labelledby','journeyDialogTitle');d.innerHTML='<header><h2 id="journeyDialogTitle"></h2></header><div class="journey-scroll"></div><footer><button type="button" class="journey-back">← Back</button></footer>';
d.querySelector('h2').textContent=title;const opener=document.activeElement;d.querySelector('.journey-back').onclick=()=>d.close();d.addEventListener('keydown',e=>{if(e.key==='Escape')e.stopPropagation();});d.addEventListener('close',()=>{d.remove();if(opener?.isConnected)opener.focus({preventScroll:true});});document.body.appendChild(d);d.showModal();return d;}
function renderDestination(reason){document.dispatchEvent(new CustomEvent('fmn:destination',{detail:{reason:reason||'display'}}));if(!$('journeySelected'))return;$('journeySelected').textContent=destination?'Saved destination: '+destination.label:'No destination selected. Nearby search still works.';$('journeyClear').hidden=!destination;const s=$('journeySummary');if(s)s.textContent=destination?'Travelling to '+destination.label:'Just looking nearby';}
function saveDestination(value){destination=core.cleanDestination(value);if(!destination)return;const saved=writeDestination();renderDestination('selected');$('journeyResults').replaceChildren();$('journeyInput').value='';app.toast(!saved?'Destination set for this session; device storage is unavailable.':destination.manual?'Saved for Maps directions only. Choose a coordinate suggestion to filter stations.':'Destination selected. Map and results now filter towards it by direction, not a road route.');}
async function searchDestination(){const query=$('journeyInput').value.trim(),state=$('journeyState').value,id=++searchSequence;searchController?.abort();const box=$('journeyResults');box.replaceChildren();if(query.length<2)return;const c=searchController=new AbortController();const timeout=setTimeout(()=>c.abort(),12000);box.setAttribute('aria-busy','true');box.textContent='Searching destinations…';
function current(){return id===searchSequence&&query===$('journeyInput').value.trim()&&state===$('journeyState').value&&$('journeyMode').value==='destination';}
try{const r=await fetch(app.api({api:'geocode',state,q:query}),{signal:c.signal});if(!r.ok)throw Error();const j=await r.json();if(!current())return;if(j.error||!Array.isArray(j.candidates))throw Error();box.replaceChildren();for(const x of j.candidates){if(x.state&&x.state!==state)continue;const clean=core.cleanDestination({...x,state});if(!clean||clean.state!==state)continue;const b=element('button',clean.label,'journey-result');b.type='button';b.onclick=()=>saveDestination(clean);box.appendChild(b);}if(!box.children.length)box.appendChild(element('p','No matching area. You can use the address below in Google Maps.'));
}catch(e){if(current()){box.replaceChildren(element('p','Destination search could not load. Try again or use the typed destination in Maps.'));const retry=element('button','Retry destination search','journey-result');retry.type='button';retry.onclick=searchDestination;box.append(retry);}}
finally{clearTimeout(timeout);if(current()){box.removeAttribute('aria-busy');const manual=element('button','Use “'+query+'” as destination in Maps','journey-result');manual.type='button';manual.onclick=()=>saveDestination({label:query+', '+state+', Australia',state,manual:true});box.append(manual);}}}
function stopSearch(){searchSequence++;clearTimeout(searchTimer);searchController?.abort();searchController=null;if($('journeyResults')){$('journeyResults').replaceChildren();$('journeyResults').removeAttribute('aria-busy');}}
function onOpen(){if(!app)return;viewport();const scroller=$('areaModal')?.querySelector('.popup-scroll');if(scroller)scroller.scrollTop=0;renderDestination();}
function onClose(){cancelLocation();stopSearch();}
function viewport(){const v=root.visualViewport;document.documentElement.style.setProperty('--journey-vh',(v?v.height:innerHeight)+'px');document.documentElement.style.setProperty('--journey-vtop',(v?v.offsetTop:0)+'px');}
function chooseNavigation(row,proceed){if(!destination){proceed(core.directionsURL(row,null,null));return;}const d=dialog('Your fuel stop & destination'),body=d.querySelector('.journey-scroll');body.append(element('p','Fuel stop: '+row.station_name),element('p','Then: '+destination.label),element('p','This opens standard Google Maps directions. FillMeNow has not checked road detours, backtracking or truck restrictions. Review the route before driving.'));const only=element('button','To this station only','journey-result');only.type='button';only.onclick=()=>{d.close();proceed(core.directionsURL(row,null,null));};body.append(only);const via=element('button','Via station to destination');via.type='button';via.id='journeyVia';via.onclick=()=>{const url=core.directionsURL(row,destination,app.getLocation());d.close();proceed(url);};d.querySelector('footer').append(via);}
function init(){app=root.FMNJourneyApp;if(!app)return;const shell=$('areaModal').querySelector('.modal'),scroll=shell.querySelector('.popup-scroll');if(!scroll)return;
const heading=scroll.querySelector('h2');heading.id='areaTitle';heading.textContent='Your location & journey';heading.tabIndex=-1;const header=element('header',undefined,'location-heading');header.append(heading);shell.prepend(header);$('areaModal').setAttribute('aria-labelledby','areaTitle');
const first=scroll.querySelector('p');if(first)first.textContent='Find fuel near your current location or a selected area. Add a destination when you are going somewhere.';
const section=element('section',undefined,'journey-fields');section.innerHTML='<label class="field">Where are you travelling? (optional)<select id="journeyMode"><option value="nearby">Just looking nearby</option><option value="destination">Going somewhere — add destination</option></select></label><div id="journeyDestination" hidden><label class="field">Destination state<select id="journeyState"><option value="QLD">Queensland</option><option value="NSW">New South Wales</option><option value="WA">Western Australia</option><option value="TAS">Tasmania</option></select></label><label class="field">Destination suburb, postcode or address<input id="journeyInput" type="search" maxlength="180" autocomplete="off" placeholder="Where are you going?"></label><div id="journeyResults" role="region" aria-label="Destination suggestions" aria-live="polite"></div><p id="journeySelected"></p><button type="button" id="journeyClear" class="journey-result">Clear destination</button><p>Choosing an area suggestion turns on the same destination-direction filter for the map, Nearby list and Best Stop. This uses geography, not road-route or truck-access verification. You can turn it off in Filters.</p></div>';
if(first)first.after(section);else scroll.prepend(section);$('journeyState').value=destination?.state||app.getPrefs().state;$('journeyMode').value=destination?'destination':'nearby';$('journeyDestination').hidden=!destination;
$('journeyMode').onchange=()=>{stopSearch();const on=$('journeyMode').value==='destination';$('journeyDestination').hidden=!on;if(!on){destination=null;writeDestination();renderDestination('cleared');}else $('journeyInput').focus();};$('journeyState').onchange=()=>{stopSearch();if($('journeyInput').value.trim().length>=2)searchDestination();};$('journeyInput').oninput=()=>{stopSearch();searchTimer=setTimeout(searchDestination,250);};$('journeyClear').onclick=()=>{destination=null;writeDestination();stopSearch();renderDestination('cleared');};
const controls=element('div',undefined,'location-recovery');controls.innerHTML='<p id="locationStatus" role="status" aria-live="polite" hidden></p><button type="button" id="locationCancel" class="journey-result" hidden>Cancel location lookup</button><button type="button" id="locationHelp" class="journey-result">Location permission help</button><button type="button" id="locationUseSelectedState" class="journey-result" hidden>Use GPS with the selected state</button>';
$('areaGps').parentElement.after(controls);$('locationCancel').onclick=()=>cancelLocation(true);$('locationHelp').onclick=help;$('locationUseSelectedState').onclick=()=>{const p=pendingPoint;if(!p)return;app.acceptGPS(p,$('stateSelect').value);};
$('locationSearch').addEventListener('input',()=>cancelLocation(true));$('stateSelect').addEventListener('change',()=>{if(controller)cancelLocation(true);});renderDestination();viewport();root.addEventListener('resize',viewport);root.visualViewport?.addEventListener('resize',viewport);root.visualViewport?.addEventListener('scroll',viewport);if($('areaModal').classList.contains('open'))onOpen();}
function openDestination(){app.openArea();$('journeyMode').value='destination';$('journeyDestination').hidden=false;$('journeyInput').focus();$('journeyDestination').scrollIntoView({block:'nearest'});}
root.FMNJourney={requestLocation,cancelLocation,onOpen,onClose,chooseNavigation,getDestination:()=>destination,openDestination};document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));
})(typeof window!=='undefined'?window:globalThis,function(){'use strict';
function cleanDestination(x){if(!x||typeof x.label!=='string'||!['QLD','NSW','WA','TAS'].includes(x.state))return null;const label=x.label.replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,220);if(label.length<2)return null;if(x.manual===true)return {label,state:x.state,manual:true};if(x.lat==null||x.lng==null||!Number.isFinite(+x.lat)||!Number.isFinite(+x.lng)||Math.abs(+x.lat)>90||Math.abs(+x.lng)>180)return null;return {label,state:x.state,lat:+x.lat,lng:+x.lng,manual:false};}
function directionsURL(row,destination,origin){if(!row||row.latitude==null||row.longitude==null||!Number.isFinite(+row.latitude)||!Number.isFinite(+row.longitude)||Math.abs(+row.latitude)>90||Math.abs(+row.longitude)>180)throw Error('invalid_station');const u=new URL('https://www.google.com/maps/dir/');u.searchParams.set('api','1');u.searchParams.set('travelmode','driving');const stop=row.latitude+','+row.longitude,d=cleanDestination(destination);u.searchParams.set('destination',d?(d.manual?d.label:d.lat+','+d.lng):stop);if(d){u.searchParams.set('waypoints',stop);if(origin&&Number.isFinite(+origin.lat)&&Number.isFinite(+origin.lng)&&origin.lat!=null&&origin.lng!=null)u.searchParams.set('origin',origin.lat+','+origin.lng);}return u.toString();}
function locate(geo,options={}){return new Promise((resolve,reject)=>{
 let done=false,timer,watch=null,watchAssigned=false,lastIssue=null;
 const signal=options.signal,set=options.setTimeout||setTimeout,clear=options.clearTimeout||clearTimeout,now=options.now||Date.now;
 function finish(error,point){if(done)return;done=true;clear(timer);signal?.removeEventListener('abort',abort);if(watchAssigned)geo.clearWatch(watch);if(error)reject(error);else resolve(point);}
 function abort(){finish({name:'AbortError'});}
 function quality(issue){lastIssue=issue;if(typeof options.onQuality==='function')options.onQuality(issue);}
 function received(position){if(done)return;const c=position?.coords,t=position?.timestamp;
  if(!c||!Number.isFinite(c.latitude)||!Number.isFinite(c.longitude)||Math.abs(c.latitude)>90||Math.abs(c.longitude)>180||!Number.isFinite(c.accuracy)||c.accuracy<0||!Number.isFinite(t)){quality({code:2});return;}
  if(now()-t>10000||t-now()>5000){quality({code:3});return;}
  if(c.accuracy>50){quality({code:'precision',accuracy:c.accuracy});return;}
  finish(null,{lat:c.latitude,lng:c.longitude,accuracy:c.accuracy,timestamp:t});
 }
 function failed(e){if(done)return;if(e?.code===1)finish({code:1});else quality({code:e?.code===3?3:2});}
 if(signal?.aborted){abort();return;}signal?.addEventListener('abort',abort,{once:true});
 timer=set(()=>finish(lastIssue||{code:3}),options.timeout||25000);
 try{const settings={enableHighAccuracy:true,timeout:20000,maximumAge:0};
  if(typeof geo?.watchPosition==='function'){watch=geo.watchPosition(received,failed,settings);watchAssigned=true;if(done)geo.clearWatch(watch);}
  else if(typeof geo?.getCurrentPosition==='function')geo.getCurrentPosition(received,failed,settings);
  else finish({code:2});
 }catch{finish({code:2});}
});}
return Object.freeze({cleanDestination,directionsURL,locate});
});