/* Nearby controls use the existing app state; verified catalogue data never comes from users' notes. */
(function(){'use strict';
const C=window.FMNNearbyCore;if(!C)return;
let app,catalog={schema_version:1,offers:[],access:[]},catalogState='loading',filters=read('fmnNearbyFilters',{}),accepted=read('fmnOfferEligibility',[]),lastList=[],lastCount=0,dialog=null,opener=null,previousOverflow='';
if(!Array.isArray(accepted))accepted=[];
function read(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x}
function context(){return app.getPrefs()}
function reloadList(){if(document.body.dataset.page==='options')app.renderOptions();}
// FMN_TRUCK_DISCOVERABILITY_20261009: absent measurements are not evidence of absent stations.
function hasMeasurements(){const now=Date.now();return catalogState==='ready'&&catalog.access.some(r=>r&&r.state===context().state&&r.status==='verified'&&Date.parse(r.expires_at)>now&&Date.parse(r.verified_at)<=now&&now-Date.parse(r.verified_at)<=90*86400000&&r.turning_access_verified===true&&Array.isArray(r.configurations)&&['height','width','length','weight'].every(k=>Number(r[k])>0));}
function useFilters(){filters=C.normaliseFilters(filters,context().radius);return filters}

function summary(n,total){const f=useFilters(),sort={value:'estimated trip cost',price:'pump price',distance:'distance',deal:'estimated cost after eligible offers'}[f.sort];return n+' of '+total+' stations · '+f.minKm+'–'+f.maxKm+' km from selected area · sorted by '+sort+(f.travel==='towards'?' · toward destination (approximate)':'')+'.'}
function modal(title){if(dialog?.open)dialog.close();opener=document.activeElement;dialog=document.createElement('dialog');dialog.className='nearby-dialog';dialog.id='nearbyDialog';dialog.setAttribute('aria-labelledby','nearbyDialogTitle');dialog.innerHTML='<header><h2 id="nearbyDialogTitle"></h2></header><div class="nearby-scroll"></div><footer><button type="button" class="nearby-back">← Back</button></footer>';dialog.querySelector('h2').textContent=title;dialog.querySelector('.nearby-back').onclick=()=>dialog.close();dialog.addEventListener('keydown',e=>{if(e.key==='Escape')e.stopPropagation()});const d=dialog;d.addEventListener('close',()=>{document.body.style.overflow=previousOverflow;d.remove();if(dialog===d)dialog=null;opener?.isConnected&&opener.focus({preventScroll:true})});document.body.appendChild(d);previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';d.showModal();return d}
function catalogueText(){return catalogState==='error'?'Station information could not load. Retry before relying on deal or access filters.':catalogState==='loading'?'Loading checked station information…':!catalog.offers.length&&!catalog.access.length?'No verified station offers or measured truck-access records have been published yet. Unknown does not mean unsuitable.':'Offers and access details are filtered by their verification dates and station IDs.'}
async function loadCatalogue(){catalogState='loading';try{const r=await fetch('/data/station-information.json',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error();const j=await r.json();if(j.schema_version!==1||!Array.isArray(j.offers)||!Array.isArray(j.access)||j.offers.length>10000||j.access.length>10000)throw Error();catalog=j;catalogState='ready'}catch{catalog={offers:[],access:[]};catalogState='error'}reloadList()}
function openFilters(){const f=useFilters(),d=modal('Nearby filters'),body=d.querySelector('.nearby-scroll');body.innerHTML='<form id="nearbyFilterForm"><div class="nearby-grid"><label class="nearby-field nearby-full">Sort by<select name="sort"><option value="value">Best estimated value</option><option value="price">Cheapest pump price</option><option value="distance">Nearest station</option><option value="deal">Best eligible fuel deal</option></select></label><label class="nearby-field nearby-full">Station deals<select name="deals"><option value="all">All stations</option><option value="active">Stations with verified active offers</option><option value="eligible">Offers I qualify for</option></select></label><label class="nearby-field">From (km)<input name="minKm" type="number" min="0" max="100" step="0.1" required inputmode="decimal"></label><label class="nearby-field">To (km)<input name="maxKm" type="number" min="1" max="100" step="0.1" required inputmode="decimal"></label></div><p>Distances are straight-line distances from your selected area or GPS point. These filters apply to the Nearby list; the map still shows the full search radius.</p><div class="nearby-warning">Distance alone does not prevent backtracking. Along-route search, road detours and truck routing are not connected yet.</div><label class="nearby-field nearby-destination-field">Destination filter<select name="travel"><option value="all">All directions</option><option value="towards">Toward saved destination · approximate</option></select></label><p class="nearby-direction-help">Uses direction and straight-line progress, not roads. It cannot guarantee no backtracking or a truck-safe approach.</p><label class="nearby-field nearby-access-field">Truck access<select name="access"><option value="all">Show all, including unverified access</option><option value="truckstops">Operator-listed truck stops · clearance unknown</option><option value="height">Recorded height clearance only</option><option value="matches">Matches all recorded dimensions only</option><option value="unknown">Clearance not recorded</option></select></label><p class="nearby-catalogue"></p><p class="truck-error" role="alert"></p></form>';
 const form=d.querySelector('form');const strict=form.querySelector('option[value="matches"]');strict.disabled=false;for(const k of ['sort','deals','minKm','maxKm','access','travel'])form.elements[k].value=f[k];d.querySelector('.nearby-access-field').hidden=!C.truckMode(context());d.querySelector('.nearby-catalogue').textContent=catalogueText();if(catalogState==='error'){const retry=el('button','Retry station information','nearby-offer-button');retry.type='button';retry.onclick=async()=>{retry.disabled=true;await loadCatalogue();d.querySelector('.nearby-catalogue').textContent=catalogueText();retry.disabled=false};body.appendChild(retry)}
 const apply=el('button','Apply filters');apply.type='submit';apply.setAttribute('form','nearbyFilterForm');d.querySelector('footer').appendChild(apply);form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;const min=Number(form.elements.minKm.value),max=Number(form.elements.maxKm.value);if(min>max){d.querySelector('.truck-error').textContent='From must be less than or equal to To.';form.elements.minKm.focus();return}filters=C.normaliseFilters({minKm:min,maxKm:max,sort:form.elements.sort.value,deals:form.elements.deals.value,access:form.elements.access.value,travel:form.elements.travel.value},context().radius);if(filters.travel==='towards'&&(!window.FMNJourney?.getDestination()||window.FMNJourney.getDestination().manual)){d.querySelector('.truck-error').textContent='Choose a destination suggestion with coordinates first. Use the Destination button on Nearby Options.';return;}const saved=write('fmnNearbyFilters',filters);d.close();app.applyRadius(Math.max(context().radius,[5,10,20,30,50,100].find(x=>x>=max)||100));app.renderOptions();if(!saved)app.toast('Filters applied for this session. Browser storage is unavailable.');};}
function reset(){filters=C.normaliseFilters({},context().radius);write('fmnNearbyFilters',filters);app.renderOptions()}
function toolbar(){if(document.getElementById('nearbyToolbar'))return;const host=el('div',undefined,'nearby-toolbar');host.id='nearbyToolbar';const button=el('button','Filters','nearby-filter-button');button.id='nearbyFilterButton';button.type='button';button.onclick=openFilters;button.setAttribute('aria-haspopup','dialog');const clear=el('button','Reset filters');clear.type='button';clear.id='nearbyReset';clear.onclick=reset;const text=el('p','','nearby-filter-summary');text.id='nearbyFilterSummary';text.setAttribute('role','status');const destination=el('button','Destination');destination.type='button';destination.id='nearbyDestination';destination.onclick=()=>window.FMNJourney?.openDestination();host.append(button,destination,clear,text);document.getElementById('optionsList').before(host)}
function radiusChanged(radius){filters=C.normaliseFilters({...filters,maxKm:radius,minKm:Math.min(Number(filters.minKm)||0,radius)},radius);write("fmnNearbyFilters",filters)}
function select(rows,prefs){lastCount=rows.length;const ctx={...prefs},f=useFilters();lastList=C.select(rows,ctx,f,catalog,accepted);if(f.travel==='towards'){const dest=window.FMNJourney?.getDestination(),origin=app.getLocation();lastList=lastList.filter(r=>window.FMNLiveCore?.toward(r,origin,dest)===true);}return lastList}

function afterRender(){toolbar();
let note=document.getElementById('truckAccessNotice');if(!note){note=el('p');note.id='truckAccessNotice';document.getElementById('optionsList').before(note);}note.hidden=!C.truckMode(context());note.className='nearby-truck-summary';
const vehicle=context().truck||{};const known=hasMeasurements();
note.textContent='Your truck: '+(vehicle.height||'—')+' m high · '+(vehicle.width||'—')+' m wide · '+(vehicle.length||'—')+' m long · '+(vehicle.weight||'—')+' t. '+(known?'Recorded limits are checked where available.':'No verified numerical clearance measurements are published here yet. Operator-listed truck facilities are separate from a confirmed fit.');

if(!lastList.length&&lastCount>0){const wider=document.getElementById('optionsWiden');if(wider)wider.hidden=true;const actions=document.querySelector('#optionsList .empty-actions');if(actions&&!document.getElementById('optionsClearFilters')){const clear=el('button','Show all · clearance unknown','btn btn-go');clear.id='optionsClearFilters';clear.type='button';clear.onclick=reset;actions.prepend(clear);if(C.truckMode(context())){const trucks=el('button','Show operator-listed truck stops','btn btn-soft');trucks.type='button';trucks.id='showListedTruckStops';trucks.onclick=()=>{filters={...useFilters(),access:'truckstops'};write('fmnNearbyFilters',filters);app.renderOptions();};actions.append(trucks);}}}
const s=document.getElementById('nearbyFilterSummary');s.textContent=summary(lastList.length,lastCount);const baseSummary=document.getElementById('optionsSummary');if(baseSummary)baseSummary.textContent='Nearby list filters · map search remains '+context().radius+' km.';document.querySelectorAll('#optionsList .option-row').forEach((row,i)=>{const x=lastList[i];if(!x)return;row.dataset.nearbyId=String(x.station_id);row.classList.toggle('best',i===0&&!x._review&&useFilters().sort==='value');const main=row.querySelector('.option-main');if(x._review)main.appendChild(el('span','Price needs checking · not used for recommendations','nearby-warning'));if(C.truckMode(context())){main.appendChild(el('span',x._access.label,'nearby-badge '+x._access.status));if(x._facility){const n=el('span','Operator lists truck facilities · numeric clearance unconfirmed. ','nearby-facility');const a=el('a','Operator details');a.href=x._facility.source_url;a.target='_blank';a.rel='noopener noreferrer';n.append(a);main.append(n);}}if(x._offers.length){const b=el('button',x._offers.length+' active offer'+(x._offers.length===1?'':'s')+(x._dealSaving>0?' · eligible saving $'+x._dealSaving.toFixed(2):' · check conditions'),'nearby-offer-button');b.type='button';b.onclick=()=>showOffers(x);main.appendChild(b);if(x._dealSaving>0)main.appendChild(el('span','After eligible offer and estimated travel: '+(x.effective-x._dealSaving/context().tank*100).toFixed(1)+'¢/L','nearby-badge match'))}})}
function emptyMessage(){const f=useFilters();if(f.travel==='towards'&&(!window.FMNJourney?.getDestination()||window.FMNJourney.getDestination().manual))return 'Choose a destination suggestion to apply the direction filter.';if(C.truckMode(context())&&f.access==='height')return 'No verified height records match your '+(context().truck?.height||'selected')+' m truck with a 0.1 m allowance. This does not mean there are no truck stops. Check operator-listed facilities or show unknown clearance.';if(C.truckMode(context())&&f.access==='truckstops')return 'No operator-listed truck facilities are in this filtered search yet. Our checked list is incomplete; unknown does not mean absent.';if(f.deals!=='all')return catalogState==='ready'?'No verified offers match these filters. Reset filters to see all nearby stations.':catalogueText();if(C.truckMode(context())&&f.access==='matches')return 'No stations have current access records matching your complete truck profile. Reset filters to include stations with unknown access.';return 'No stations match this distance range. Adjust or reset the Nearby filters.'}
function showOffers(row){const d=modal('Station offers'),body=d.querySelector('.nearby-scroll');body.appendChild(el('p',row.station_name));body.appendChild(el('p','Pump prices are unchanged. Offer savings are estimates, capped to the published litres, and apply only when you qualify. Offers do not stack.'));
 for(const o of C.offersFor(row,context(),catalog,accepted)){const card=el('article',undefined,'offer-card');card.append(el('h3',o.title),el('p',o.terms),el('p','Ends '+new Date(o.ends_at).toLocaleString('en-AU')+' · '+o.discount_cpl+'¢/L discount · up to '+o.max_litres+' L'));const link=el('a','Official offer conditions');link.href=o.terms_url;link.target='_blank';link.rel='noopener noreferrer';card.append(link);if(o.eligibility==='conditions'){const label=el('label',undefined,'offer-consent'),check=document.createElement('input');check.type='checkbox';check.checked=accepted.includes(o.key);const text=el('span','I have checked the conditions and qualify for this offer.');label.append(check,text);check.onchange=()=>{accepted=accepted.filter(k=>k!==o.key);if(check.checked)accepted.push(o.key);accepted=accepted.slice(-100);write('fmnOfferEligibility',accepted);reloadList()};card.append(label)}body.append(card)}}
function badges(row,prefs){const parts=[];if(C.priceReview(row))parts.push('<div class="station-mini price-review">Price needs checking. This recorded value is not used in Best Stop or price alerts. Confirm with the station; no replacement price has been guessed.</div>');if(C.truckMode(prefs)){const a=C.truckAccess(row,prefs,catalog);parts.push('<div class="station-mini price-review">'+a.label+'. Truck routing is not connected; confirm the approach, clearance and turning space before travel.</div>')}return parts.join('')}
function buildTruck(){const parent=document.getElementById('drawer-vehicle');if(!parent||document.getElementById('truckProfile'))return;const panel=el('section',undefined,'truck-profile');panel.id='truckProfile';panel.innerHTML='<label class="truck-toggle"><input type="checkbox" id="truckModeToggle">Truck mode</label><p class="truck-note">Record your actual loaded vehicle or combination. Your dimensions stay on this device. A station brand or diesel pump is not evidence that your truck will fit.</p><div id="truckDimensions" hidden><div class="nearby-grid"><label class="nearby-field nearby-full">Configuration<select id="truckConfiguration"><option value="rigid">Rigid truck</option><option value="articulated">Articulated / semi-trailer</option><option value="b-double">B-double</option><option value="road-train">Road train</option><option value="other">Other combination</option></select></label><label class="nearby-field">Height (m)<input id="truckHeight" type="number" min="0.5" max="10" step="0.01" inputmode="decimal" placeholder="e.g. 4.3"></label><label class="nearby-field">Width (m)<input id="truckWidth" type="number" min="0.5" max="10" step="0.01" inputmode="decimal" placeholder="e.g. 2.5"></label><label class="nearby-field">Total length (m)<input id="truckLength" type="number" min="1" max="70" step="0.01" inputmode="decimal" placeholder="Including trailers"></label><label class="nearby-field">Loaded weight (t)<input id="truckWeight" type="number" min="0.5" max="300" step="0.01" inputmode="decimal" placeholder="Whole combination"></label></div><p class="truck-note">Use the highest loaded point, operating width (including projecting equipment), full length including trailers, and total loaded weight. This is not a permit or legal-access check.</p><div class="nearby-warning">Station access is not verified until measured, dated records are available. Standard directions do not use these truck dimensions.</div></div><p id="truckSaveError" class="truck-error" role="alert"></p>';parent.querySelector('#saveVehicle').before(panel);panel.querySelector('#truckModeToggle').onchange=e=>{app.setVehicle(e.target.checked?'truck':'car');syncVehicle()};}
function syncVehicle(){if(!app)return;buildTruck();const p=context(),active=C.truckMode(p),t=p.truck||{};document.getElementById('truckModeToggle').checked=active;document.getElementById('truckDimensions').hidden=!active;for(const k of ['height','width','length','weight'])document.getElementById('truck'+k[0].toUpperCase()+k.slice(1)).value=t[k]||'';document.getElementById('truckConfiguration').value=t.configuration||'rigid';document.getElementById('truckSaveError').textContent='';const draft=read('fmnVehicleDraft',null);if(draft?.vehicle===p.vehicle){for(const [id,value] of Object.entries(draft.values||{})){const n=document.getElementById(id);if(n)n.value=value;}}installVehicleAutosave();}
function installVehicleAutosave(){
const panel=document.getElementById('drawer-vehicle');if(!document.getElementById('vehicleSaveStatus')){const n=el('p','Valid changes save automatically on this device.','vehicle-save-status');n.id='vehicleSaveStatus';n.role='status';document.getElementById('saveVehicle').after(n);}
if(panel.dataset.autosave)return;panel.dataset.autosave='1';panel.addEventListener('input',e=>{if(e.target.matches('input[type=number],select'))flushVehicle();});panel.addEventListener('change',e=>{if(e.target.matches('input[type=number],select'))flushVehicle();});}
function flushVehicle(){
const p=context(),ids=['tankInput','economyInput','truckHeight','truckWidth','truckLength','truckWeight','truckConfiguration'],values={};
for(const id of ids){const n=document.getElementById(id);if(n)values[id]=n.value;}
const draftSaved=write('fmnVehicleDraft',{vehicle:p.vehicle,values});const tank=document.getElementById('tankInput'),economy=document.getElementById('economyInput'),status=document.getElementById('vehicleSaveStatus');
let error='';if(!tank.value||!economy.value||!tank.checkValidity()||!economy.checkValidity())error='Enter a valid fill size and fuel use.';
const t={configuration:values.truckConfiguration};for(const k of ['height','width','length','weight'])t[k]=values['truck'+k[0].toUpperCase()+k.slice(1)];const validation=C.validateTruck(t);if(C.truckMode(p)&&!validation.ok)error='Complete a valid '+validation.field+' to apply the truck profile.';
if(error){if(status){status.textContent=(draftSaved?'Draft kept. ':'Draft not saved. ')+error;status.dataset.error='true';}return false;}
const saved=app.saveVehicleQuiet({tank:+tank.value,economy:+economy.value,vehicle:p.vehicle,truck:C.truckMode(p)?validation.truck:p.truck});
if(saved){try{localStorage.removeItem('fmnVehicleDraft')}catch{}}
if(status){status.textContent=saved?'Saved on this device.':'Not saved: device storage is unavailable. Keep the app open and retry.';status.dataset.error=String(!saved);}return saved;
}
function saveVehicle(){const ok=flushVehicle();document.getElementById('truckSaveError').textContent=ok?'':'Check the fields and save status below.';if(ok)app.toast('Vehicle saved on this device');return ok;}

function navigate(row,proceed){if(!C.truckMode(context())){proceed();return}const d=modal('Check truck access first'),body=d.querySelector('.nearby-scroll'),status=C.truckAccess(row,context(),catalog);body.append(el('p',row.station_name),el('div',status.label,'nearby-warning'),el('p','Truck-aware routing is not connected. Standard Google Maps directions do not use your height, width, length or loaded weight. Check road restrictions, the entrance, canopy clearance and turning space yourself.'));const button=el('button','Standard directions');button.type='button';button.onclick=()=>{d.close();proceed()};d.querySelector('footer').appendChild(button)}
window.FMNNearbyUI={flushVehicle,radiusChanged,select,afterRender,summary,emptyMessage,badges,syncVehicle,saveVehicle,navigate,openFilters};
document.addEventListener('DOMContentLoaded',()=>{app=window.FMNNearbyApp;if(!app)return;filters=C.normaliseFilters(filters,context().radius);toolbar();syncVehicle();loadCatalogue();document.addEventListener('fmn:destination',reloadList);});
})();
