/* FillMeNow guided support. Questions stay in memory; only confirmed reports leave the device. */
(function(){'use strict';
const VERSION='support-qld-20261008',API='https://psytztnkeeymavzmpomv.supabase.co/functions/v1/fueldrop';
const topics={
 loading:{title:'Opening screen / flashing',answer:'Close and reopen FillMeNow while online to load the latest app files. If the opening screen is clipped, tell us your screen size, whether you installed the app, and what flashes. Do not reset your saved settings first.'},
 map:{title:'Map and station icons',answer:'The small arrow beneath each company logo points to the station location supplied by the fuel-data provider. Zoom in to separate nearby stations. Tapping overlapping pins opens a station chooser. The stations button opens the full comparison list. Icons must not cover the map buttons.'},
 prices:{title:'Prices and Best Stop',answer:'Best Stop compares pump price and estimated round-trip fuel cost using your vehicle settings. It is not a live traffic or route-time calculation. Diesel compares available regular and premium diesel; the actual grade is labelled. Confirm the price and grade at the pump.'},
 location:{title:'Location and Queensland',answer:'Use the search icon, select your state, then search a suburb or postcode, or choose Use current location. GPS needs your permission. Available states are shown in that selector. Queensland stays marked as connecting until its production feed has supplied valid data.'},
 dash:{title:'Moving Dash',answer:'Swipe Best Stop down to collapse it. Drag the small rounded Dash tile to a comfortable thumb position; the position is remembered on this device. Tap Dash to reopen Best Stop. Dragging moves the tile rather than opening it.'},
 alerts:{title:'Price alerts',answer:'Open Alerts, choose your schedule and settings, and save. Turning alerts off stops them on this device. Browser notifications need permission and browser support. Native iPhone push is not yet configured; a successful local test is not proof that scheduled remote notifications will arrive.'},
 accessibility:{title:'Text, buttons and accessibility',answer:'Text and buttons should remain readable without overlapping. Tell us which screen is affected and whether you use enlarged text, screen zoom, a keyboard or a screen reader. Report the problem below so it can be tested.'},
 privacy:{title:'Privacy and reports',answer:'This help chat uses built-in app guidance, not a human operator. Chat questions are not sent or stored by this helper. Only a report you explicitly submit is saved privately, for up to 90 days. No name, email, exact GPS location, saved stations or passwords are requested. Weekly repository tasks are anonymised. You can delete your last report from this device after submitting it.'},
 suggestion:{title:'Suggest an improvement',answer:'Describe what you were trying to do and how the app could make it easier. Submit it as a suggestion below. Reports are reviewed weekly; a report is not a promise that a change will be made.'},
 other:{title:'Other app question',answer:'I help with FillMeNow: getting started, searching, maps, prices, Dash, saved stations, alerts and app glitches. Pick a topic or describe the problem. I cannot answer unrelated questions or confirm a fix that has not been tested.'}
};
let dialog,log,input,form,category,notes,consent,send,result,deleteBtn,opener,lastQuestion='',lastTopic='other',deviceToken='',receipt='',busy=false,blocked=[];
function read(k){try{return localStorage.getItem(k)||''}catch{return ''}}
function store(k,v){try{localStorage.setItem(k,v)}catch{}}
function message(text,who){const p=document.createElement('p');p.className='help-message '+who;p.textContent=text;log.appendChild(p);while(log.children.length>30)log.firstChild.remove();p.scrollIntoView({block:'nearest'});}
function classify(text){const s=String(text).toLowerCase();
 if(/privacy|personal|email|name|data|delete|complaint record/.test(s))return 'privacy';
 if(/flash|flicker|opening|startup|start up|loading|blank|white screen|launch|crash|freez/.test(s))return 'loading';
 if(/dash|mascot|swip|drag|rounded/.test(s))return 'dash';
 if(/gps|location|queensland|qld|brisbane|suburb|postcode|state|search|radius/.test(s))return 'location';
 if(/map|icon|station.*button|overlap|logo|zoom|arrow|pin/.test(s))return 'map';
 if(/alert|notification|push|schedule/.test(s))return 'alerts';
 if(/price|diesel|petrol|best stop|cost|saving|fuel grade/.test(s))return 'prices';
 if(/font|text|small|size|read|screen reader|keyboard|accessibility/.test(s))return 'accessibility';
 if(/suggest|improve|would like|feature|recommend/.test(s))return 'suggestion';return 'other';}
function answer(text){const trimmed=String(text).trim().slice(0,700);if(!trimmed)return;lastQuestion=trimmed;lastTopic=classify(trimmed);message(trimmed,'user');
 if(/install|home screen/.test(trimmed.toLowerCase()))message('Open More → Install App. On iPhone, use Safari → Share → Add to Home Screen. Installing the web app is different from an App Store release. If installation fails, report your browser and what the install screen says.','bot');
 else if(/saved|favourite|favorite/.test(trimmed.toLowerCase()))message('Open a station’s details and choose Save. To remove it later, open Saved and tap Remove under that station. This only removes your saved shortcut; the station stays on the map. Your choice is remembered on this device after reopening the app.','bot');
 else message(topics[lastTopic].answer,'bot');
 if(/bug|glitch|broken|not work|doesn.t|complain|wrong|overlap|flash|flicker|missing|crash/.test(trimmed.toLowerCase()))message('Which screen were you using, what did you expect, and what happened instead? Use “Report this problem” to review a private note. Nothing is submitted until you confirm.','bot');input.value='';}
function viewport(){if(!dialog)return;const v=window.visualViewport;dialog.style.setProperty('--help-height',(v?v.height:innerHeight)+'px');dialog.style.setProperty('--help-top',(v?v.offsetTop:0)+'px');}
function build(){if(dialog)return;dialog=document.createElement('section');dialog.id='fmnHelp';dialog.className='fmn-help';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-labelledby','fmnHelpTitle');
 dialog.innerHTML='<div class="help-shell"><header class="help-header"><h2 id="fmnHelpTitle">Ask Dash</h2><p>Guided app help · not a human operator</p></header><div class="help-scroll"><div id="fmnHelpLog" class="help-log" role="log" aria-live="polite" aria-relevant="additions"></div><div class="help-topics" aria-label="Help topics"></div><button type="button" class="help-report-open">Report this problem</button><form class="help-report" hidden><h3>Send a private report</h3><p>What happened, what did you expect, and how can we reproduce it? Please leave out names, contact details and exact addresses.</p><label>Topic<select name="category"></select></label><label>Your note<textarea name="note" minlength="10" maxlength="2000" rows="4" required></textarea></label><label class="help-honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><label class="help-consent"><input type="checkbox" name="consent" required><span>I agree to send this note, app version, browser family, current screen and screen size for private investigation. GPS and contact details are not attached automatically; please do not type them into the note. Anonymised tasks may be added to the repository.</span></label><button type="submit" class="help-submit">Send report</button><p class="help-result" role="status"></p><button type="button" class="help-delete" hidden>Delete my last report</button></form></div><form class="help-composer"><label class="help-sr" for="fmnHelpInput">Ask about the app</label><input id="fmnHelpInput" maxlength="700" placeholder="Ask about the app or a glitch…" autocomplete="off"><button type="submit" aria-label="Send question">Ask</button></form><footer class="help-footer"><button type="button" class="help-back">← Back</button><small>Reports reviewed weekly</small></footer></div>';
 document.body.appendChild(dialog);log=dialog.querySelector('.help-log');input=dialog.querySelector('#fmnHelpInput');form=dialog.querySelector('.help-report');category=form.elements.category;notes=form.elements.note;consent=form.elements.consent;send=form.querySelector('.help-submit');result=form.querySelector('.help-result');deleteBtn=form.querySelector('.help-delete');
 Object.entries(topics).forEach(([key,t])=>{const o=document.createElement('option');o.value=key;o.textContent=t.title;category.appendChild(o)});
 ['loading','map','location','dash','prices','alerts','privacy'].forEach(key=>{const b=document.createElement('button');b.type='button';b.textContent=topics[key].title;b.onclick=()=>{lastTopic=key;lastQuestion=topics[key].title;message(topics[key].title,'user');message(topics[key].answer,'bot')};dialog.querySelector('.help-topics').appendChild(b)});
 dialog.querySelector('.help-composer').onsubmit=e=>{e.preventDefault();answer(input.value)};
 dialog.querySelector('.help-report-open').onclick=()=>{form.hidden=false;if(!notes.value){category.value=lastTopic;notes.value=lastQuestion.length>=10?lastQuestion:'';}notes.focus();form.scrollIntoView({block:'nearest'})};
 dialog.querySelector('.help-back').onclick=close;form.onsubmit=submit;deleteBtn.onclick=removeLast;
 dialog.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close()}if(e.key==='Tab'){const a=[...dialog.querySelectorAll('button,input,textarea,select,[tabindex]')].filter(x=>!x.disabled&&x.tabIndex>=0&&x.getClientRects().length);if(!a.length)return;const first=a[0],last=a[a.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
 message('Hi, I’m Dash’s app-help assistant. What are you trying to do, or what went wrong? Choose a topic or ask below. Use the report button when you need us to investigate.','bot');
 deviceToken=read('fmnSupportDevice');receipt=read('fmnSupportReceipt');if(receipt&&deviceToken)deleteBtn.hidden=false;
}
function open(){build();if(dialog.classList.contains('open'))return;opener=document.activeElement;dialog.hidden=false;dialog.classList.add('open');blocked=[...document.body.children].filter(e=>e!==dialog&&!['SCRIPT','STYLE','LINK'].includes(e.tagName)).map(e=>({e,inert:e.inert}));blocked.forEach(x=>{x.e.inert=true});document.body.classList.add('help-open');viewport();dialog.querySelector('.help-back').focus({preventScroll:true});}
function close(){if(!dialog)return;dialog.classList.remove('open');dialog.hidden=true;blocked.forEach(x=>{x.e.inert=x.inert});blocked=[];document.body.classList.remove('help-open');if(opener?.isConnected&&!opener.closest('[inert]'))opener.focus({preventScroll:true});}
function token(){if(!/^[a-f0-9]{64}$/.test(deviceToken)){deviceToken=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');store('fmnSupportDevice',deviceToken)}return deviceToken;}
function browserFamily(){const u=navigator.userAgent;return /Edg/.test(u)?'Edge':/Firefox/.test(u)?'Firefox':/Chrome|CriOS/.test(u)?'Chrome':/Safari/.test(u)?'Safari':'Other';}
async function submit(e){e.preventDefault();if(busy||!form.reportValidity())return;busy=true;send.disabled=true;result.textContent='Sending…';
 const messageText=notes.value.trim(),signature=JSON.stringify([messageText,category.value]);
 if(form.dataset.requestSignature!==signature){form.dataset.requestId=crypto.randomUUID();form.dataset.requestSignature=signature;}
 const body={request_id:form.dataset.requestId,device_token:token(),category:category.value,message:messageText,consent:consent.checked,website:form.elements.website.value,diagnostics:{app_version:VERSION,browser:browserFamily(),viewport:Math.round(innerWidth)+'x'+Math.round(innerHeight),screen:document.body.dataset.page||'support'}};
 try{const r=await fetch(API+'?api=support-report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const j=await r.json();if(!r.ok||j.ok!==true||!(/^[a-f0-9-]{36}$/i).test(j.receipt||''))throw Error(r.status===429?'rate':r.status===400?'invalid':'send');receipt=j.receipt;store('fmnSupportReceipt',receipt);result.textContent='Report saved privately. Reference: '+receipt+'. It is queued for the weekly review; this does not mean the issue has been fixed.';delete form.dataset.requestId;delete form.dataset.requestSignature;notes.value='';consent.checked=false;deleteBtn.hidden=false;message('Your report was saved for investigation. Thank you for helping improve FillMeNow.','bot');}
 catch(err){result.textContent=err.message==='rate'?'Too many reports in a short time. Please try again later.':err.message==='invalid'?'Please check your note and consent, then retry. Your note is still here.':'Delivery not confirmed. Check your connection and retry the same note to avoid duplicate reports. Your note is still here.';}
 finally{busy=false;send.disabled=false;}}
async function removeLast(){if(busy||!receipt)return;busy=true;deleteBtn.disabled=true;try{const r=await fetch(API+'?api=support-delete',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({receipt,device_token:token()}),signal:AbortSignal.timeout(15000)});const j=await r.json();if(!r.ok||j.ok!==true)throw Error();receipt='';store('fmnSupportReceipt','');deleteBtn.hidden=true;result.textContent='Your last report has been deleted.';}catch{result.textContent='Deletion was not confirmed. Please retry while online.';}finally{busy=false;deleteBtn.disabled=false}}
window.FMNHelp={open,close,classify,version:VERSION};window.addEventListener('resize',viewport);if(window.visualViewport){visualViewport.addEventListener('resize',viewport);visualViewport.addEventListener('scroll',viewport)}
window.addEventListener('DOMContentLoaded',()=>{if(new URL(location.href).searchParams.get('help')==='1')open()});
})();
